package com.ragchat.api.model

/**
 * Sender role for a chat message.
 */
public enum class MessageRole {
    /**
     * End-user prompt message.
     */
    USER,

    /**
     * Assistant response message generated by the SDK.
     */
    ASSISTANT,

    /**
     * System instruction framing conversation behavior.
     */
    SYSTEM,
}

/**
 * Represents a single message in a conversation session.
 *
 * @property id Unique message identifier.
 * @property role Role of the author (user, assistant, system).
 * @property content Text body of the message.
 * @property timestampEpochMs Creation epoch timestamp in milliseconds.
 * @property citations Citations backing this message if generated by the assistant.
 */
public data class ChatMessage(
    val id: String,
    val role: MessageRole,
    val content: String,
    val timestampEpochMs: Long = System.currentTimeMillis(),
    val citations: List<Citation> = emptyList(),
)
