package com.ragchat.api.model

import com.ragchat.api.error.SdkError

/**
 * Event streamed from an LLM inference generation cycle.
 */
public sealed interface LlmEvent {
    /**
     * Incremental token generated by the model.
     *
     * @property text The generated text fragment.
     */
    public data class Token(
        val text: String,
    ) : LlmEvent

    /**
     * Generation metadata emitted during or after generation.
     *
     * @property promptTokens Number of tokens in the prompt.
     * @property candidateTokens Number of tokens produced in the generation.
     * @property finishReason Optional termination reason (e.g., stop, max_tokens).
     */
    public data class Metadata(
        val promptTokens: Int,
        val candidateTokens: Int,
        val finishReason: String? = null,
    ) : LlmEvent

    /**
     * Error encountered during model streaming.
     *
     * @property error The sanitized [SdkError] instance.
     */
    public data class Error(
        val error: SdkError,
    ) : LlmEvent

    /**
     * Signals completion of generation stream.
     */
    public data object Done : LlmEvent
}
