package com.ragchat.api.chat

import com.ragchat.api.error.SdkError
import com.ragchat.api.model.Answer
import com.ragchat.api.model.Citation

/**
 * Sealed event stream emitted during chat query processing.
 */
public sealed interface ChatEvent {
    /**
     * Emitted when user query is reformulated using conversational history.
     *
     * @property original Raw user prompt.
     * @property rewritten Anaphora-resolved standalone query.
     */
    public data class QueryRewritten(
        val original: String,
        val rewritten: String,
    ) : ChatEvent

    /**
     * Emitted when document retrieval completes.
     *
     * @property chunkCount Number of context chunks retrieved.
     */
    public data class RetrievalComplete(
        val chunkCount: Int,
    ) : ChatEvent

    /**
     * Streaming token chunk generated by the model.
     *
     * @property text Incremental token text.
     */
    public data class Token(
        val text: String,
    ) : ChatEvent

    /**
     * Source citation identified during or after response generation.
     *
     * @property citation Grounded citation linking text to document chunk.
     */
    public data class CitationFound(
        val citation: Citation,
    ) : ChatEvent

    /**
     * Diagnostic usage metadata for token counts and completion reasons.
     *
     * @property promptTokens Tokens consumed by input prompt.
     * @property candidateTokens Tokens generated by model.
     * @property finishReason Model completion termination reason.
     */
    public data class Metadata(
        val promptTokens: Int,
        val candidateTokens: Int,
        val finishReason: String? = null,
    ) : ChatEvent

    /**
     * Final completed answer containing aggregated text, citations, and metadata.
     *
     * @property answer Finalized answer instance.
     */
    public data class Done(
        val answer: Answer,
    ) : ChatEvent

    /**
     * Error encountered during chat processing.
     *
     * @property error Sanitized SDK error.
     */
    public data class Error(
        val error: SdkError,
    ) : ChatEvent
}
